server:
port: 8083
servlet:
context-path: /api
spring:
datasource:
driver-class-name: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/pfe
username: root
password: root
jpa:
show_sql: true
generate-ddl: true
hibernate:
ddl-auto: create