server:
  port: 8083
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: mysql
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create